/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/brJD5cEK5Sf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"

export function FAQ() {
  return (
    <div className="w-full max-w-3xl mx-auto py-12 md:py-20">
      <div className="space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Frequently Asked Questions</h1>
          <p className="mt-2 text-muted-foreground md:text-xl">Get answers to your questions about TaskBidder.</p>
        </div>
        <Accordion type="single" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger className="flex items-center justify-between">
              <h3 className="text-lg font-medium">How does TaskBidder work for freelancers?</h3>
              {/* <ChevronDownIcon className="h-5 w-5 text-muted-foreground" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <div className="prose text-muted-foreground">
                <p>
                  TaskBidder is a platform that connects freelancers with clients who need their services. As a
                  freelancer, you can create a profile, showcase your skills and experience, and bid on projects that
                  match your expertise. Once you're hired, you'll work directly with the client to complete the project.
                </p>
                <p>
                  TaskBidder takes care of the payment processing and communication, so you can focus on delivering
                  high-quality work. You'll get paid securely through the platform, and you can also use the built-in
                  tools to track your earnings and manage your projects.
                </p>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger className="flex items-center justify-between">
              <h3 className="text-lg font-medium">What types of projects can I find on TaskBidder?</h3>
              {/* <ChevronDownIcon className="h-5 w-5 text-muted-foreground" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <div className="prose text-muted-foreground">
                <p>
                  TaskBidder offers a wide range of project types, including web development, graphic design, content
                  writing, virtual assistance, and more. Clients post their project requirements, and freelancers can
                  browse and bid on the ones that match their skills and expertise.
                </p>
                <p>
                  Whether you're a seasoned professional or just starting out, you'll find opportunities that fit your
                  background and interests. The platform is designed to help you connect with clients who value your
                  unique skills and experience.
                </p>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger className="flex items-center justify-between">
              <h3 className="text-lg font-medium">How do I get paid on TaskBidder?</h3>
              {/* <ChevronDownIcon className="h-5 w-5 text-muted-foreground" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <div className="prose text-muted-foreground">
                <p>
                  TaskBidder uses secure payment processing to ensure that you get paid on time and without any hassle.
                  When you're hired for a project, the client will make the payment through the platform. The funds will
                  be held in escrow until you complete the work to the client's satisfaction.
                </p>
                <p>
                  Once the project is approved, you'll receive your payment directly to your preferred payment method,
                  such as a bank account or digital wallet. TaskBidder takes a small commission from each transaction,
                  but you'll always know exactly how much you'll be earning.
                </p>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger className="flex items-center justify-between">
              <h3 className="text-lg font-medium">How do I build a strong profile on TaskBidder?</h3>
              {/* <ChevronDownIcon className="h-5 w-5 text-muted-foreground" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <div className="prose text-muted-foreground">
                <p>
                  Building a strong profile on TaskBidder is key to attracting clients and getting hired for projects.
                  Start by creating a detailed profile that showcases your skills, experience, and portfolio. Be sure to
                  include relevant keywords, certifications, and any other information that can help clients understand
                  your expertise.
                </p>
                <p>
                  Actively engage with the TaskBidder community by responding to messages, leaving reviews, and
                  participating in discussions. This will help you build a positive reputation and increase your
                  visibility on the platform. Additionally, consider offering competitive rates and delivering
                  high-quality work to earn positive feedback from your clients.
                </p>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger className="flex items-center justify-between">
              <h3 className="text-lg font-medium">What is the process for disputing a project?</h3>
              {/* <ChevronDownIcon className="h-5 w-5 text-muted-foreground" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <div className="prose text-muted-foreground">
                <p>
                  TaskBidder has a clear process for handling disputes between freelancers and clients. If you're not
                  satisfied with the client's feedback or the final payment, you can initiate a dispute through the
                  platform.
                </p>
                <p>
                  The TaskBidder team will review the details of the project and the communication between you and the
                  client. They'll then work with both parties to try to resolve the issue amicably. If necessary, they
                  may involve a third-party mediator to help reach a fair resolution.
                </p>
                <p>
                  It's important to follow the dispute process carefully and provide all the necessary documentation to
                  support your case. TaskBidder is committed to ensuring a fair and transparent process for all parties
                  involved.
                </p>
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  )
}

function ChevronDownIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
